// Code generated by ent, DO NOT EDIT.

package netbirdsettings

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the netbirdsettings type in the database.
	Label = "netbird_settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldManagementURL holds the string denoting the management_url field in the database.
	FieldManagementURL = "management_url"
	// FieldAccessToken holds the string denoting the access_token field in the database.
	FieldAccessToken = "access_token"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// Table holds the table name of the netbirdsettings in the database.
	Table = "netbird_settings"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "tenants"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_netbird"
)

// Columns holds all SQL columns for netbirdsettings fields.
var Columns = []string{
	FieldID,
	FieldManagementURL,
	FieldAccessToken,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultManagementURL holds the default value on creation for the "management_url" field.
	DefaultManagementURL string
	// DefaultAccessToken holds the default value on creation for the "access_token" field.
	DefaultAccessToken string
)

// OrderOption defines the ordering options for the NetbirdSettings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByManagementURL orders the results by the management_url field.
func ByManagementURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagementURL, opts...).ToFunc()
}

// ByAccessToken orders the results by the access_token field.
func ByAccessToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessToken, opts...).ToFunc()
}

// ByTenantCount orders the results by tenant count.
func ByTenantCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTenantStep(), opts...)
	}
}

// ByTenant orders the results by tenant terms.
func ByTenant(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, TenantTable, TenantColumn),
	)
}
