// Code generated by ent, DO NOT EDIT.

package netbirdsettings

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/open-uem/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldLTE(FieldID, id))
}

// ManagementURL applies equality check predicate on the "management_url" field. It's identical to ManagementURLEQ.
func ManagementURL(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldEQ(FieldManagementURL, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldEQ(FieldAccessToken, v))
}

// ManagementURLEQ applies the EQ predicate on the "management_url" field.
func ManagementURLEQ(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldEQ(FieldManagementURL, v))
}

// ManagementURLNEQ applies the NEQ predicate on the "management_url" field.
func ManagementURLNEQ(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldNEQ(FieldManagementURL, v))
}

// ManagementURLIn applies the In predicate on the "management_url" field.
func ManagementURLIn(vs ...string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldIn(FieldManagementURL, vs...))
}

// ManagementURLNotIn applies the NotIn predicate on the "management_url" field.
func ManagementURLNotIn(vs ...string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldNotIn(FieldManagementURL, vs...))
}

// ManagementURLGT applies the GT predicate on the "management_url" field.
func ManagementURLGT(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldGT(FieldManagementURL, v))
}

// ManagementURLGTE applies the GTE predicate on the "management_url" field.
func ManagementURLGTE(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldGTE(FieldManagementURL, v))
}

// ManagementURLLT applies the LT predicate on the "management_url" field.
func ManagementURLLT(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldLT(FieldManagementURL, v))
}

// ManagementURLLTE applies the LTE predicate on the "management_url" field.
func ManagementURLLTE(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldLTE(FieldManagementURL, v))
}

// ManagementURLContains applies the Contains predicate on the "management_url" field.
func ManagementURLContains(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldContains(FieldManagementURL, v))
}

// ManagementURLHasPrefix applies the HasPrefix predicate on the "management_url" field.
func ManagementURLHasPrefix(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldHasPrefix(FieldManagementURL, v))
}

// ManagementURLHasSuffix applies the HasSuffix predicate on the "management_url" field.
func ManagementURLHasSuffix(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldHasSuffix(FieldManagementURL, v))
}

// ManagementURLIsNil applies the IsNil predicate on the "management_url" field.
func ManagementURLIsNil() predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldIsNull(FieldManagementURL))
}

// ManagementURLNotNil applies the NotNil predicate on the "management_url" field.
func ManagementURLNotNil() predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldNotNull(FieldManagementURL))
}

// ManagementURLEqualFold applies the EqualFold predicate on the "management_url" field.
func ManagementURLEqualFold(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldEqualFold(FieldManagementURL, v))
}

// ManagementURLContainsFold applies the ContainsFold predicate on the "management_url" field.
func ManagementURLContainsFold(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldContainsFold(FieldManagementURL, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenIsNil applies the IsNil predicate on the "access_token" field.
func AccessTokenIsNil() predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldIsNull(FieldAccessToken))
}

// AccessTokenNotNil applies the NotNil predicate on the "access_token" field.
func AccessTokenNotNil() predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldNotNull(FieldAccessToken))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.FieldContainsFold(FieldAccessToken, v))
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.NetbirdSettings {
	return predicate.NetbirdSettings(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NetbirdSettings) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NetbirdSettings) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NetbirdSettings) predicate.NetbirdSettings {
	return predicate.NetbirdSettings(sql.NotPredicates(p))
}
