// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/open-uem/ent/netbirdsettings"
)

// NetbirdSettings is the model entity for the NetbirdSettings schema.
type NetbirdSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ManagementURL holds the value of the "management_url" field.
	ManagementURL string `json:"management_url,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken string `json:"access_token,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NetbirdSettingsQuery when eager-loading is set.
	Edges        NetbirdSettingsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NetbirdSettingsEdges holds the relations/edges for other nodes in the graph.
type NetbirdSettingsEdges struct {
	// Tenant holds the value of the tenant edge.
	Tenant []*Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading.
func (e NetbirdSettingsEdges) TenantOrErr() ([]*Tenant, error) {
	if e.loadedTypes[0] {
		return e.Tenant, nil
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*NetbirdSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case netbirdsettings.FieldID:
			values[i] = new(sql.NullInt64)
		case netbirdsettings.FieldManagementURL, netbirdsettings.FieldAccessToken:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the NetbirdSettings fields.
func (ns *NetbirdSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case netbirdsettings.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ns.ID = int(value.Int64)
		case netbirdsettings.FieldManagementURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field management_url", values[i])
			} else if value.Valid {
				ns.ManagementURL = value.String
			}
		case netbirdsettings.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				ns.AccessToken = value.String
			}
		default:
			ns.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the NetbirdSettings.
// This includes values selected through modifiers, order, etc.
func (ns *NetbirdSettings) Value(name string) (ent.Value, error) {
	return ns.selectValues.Get(name)
}

// QueryTenant queries the "tenant" edge of the NetbirdSettings entity.
func (ns *NetbirdSettings) QueryTenant() *TenantQuery {
	return NewNetbirdSettingsClient(ns.config).QueryTenant(ns)
}

// Update returns a builder for updating this NetbirdSettings.
// Note that you need to call NetbirdSettings.Unwrap() before calling this method if this NetbirdSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (ns *NetbirdSettings) Update() *NetbirdSettingsUpdateOne {
	return NewNetbirdSettingsClient(ns.config).UpdateOne(ns)
}

// Unwrap unwraps the NetbirdSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ns *NetbirdSettings) Unwrap() *NetbirdSettings {
	_tx, ok := ns.config.driver.(*txDriver)
	if !ok {
		panic("ent: NetbirdSettings is not a transactional entity")
	}
	ns.config.driver = _tx.drv
	return ns
}

// String implements the fmt.Stringer.
func (ns *NetbirdSettings) String() string {
	var builder strings.Builder
	builder.WriteString("NetbirdSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ns.ID))
	builder.WriteString("management_url=")
	builder.WriteString(ns.ManagementURL)
	builder.WriteString(", ")
	builder.WriteString("access_token=")
	builder.WriteString(ns.AccessToken)
	builder.WriteByte(')')
	return builder.String()
}

// NetbirdSettingsSlice is a parsable slice of NetbirdSettings.
type NetbirdSettingsSlice []*NetbirdSettings
