// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/agent"
	"github.com/open-uem/ent/netbird"
	"github.com/open-uem/ent/predicate"
)

// NetbirdQuery is the builder for querying Netbird entities.
type NetbirdQuery struct {
	config
	ctx        *QueryContext
	order      []netbird.OrderOption
	inters     []Interceptor
	predicates []predicate.Netbird
	withOwner  *AgentQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NetbirdQuery builder.
func (nq *NetbirdQuery) Where(ps ...predicate.Netbird) *NetbirdQuery {
	nq.predicates = append(nq.predicates, ps...)
	return nq
}

// Limit the number of records to be returned by this query.
func (nq *NetbirdQuery) Limit(limit int) *NetbirdQuery {
	nq.ctx.Limit = &limit
	return nq
}

// Offset to start from.
func (nq *NetbirdQuery) Offset(offset int) *NetbirdQuery {
	nq.ctx.Offset = &offset
	return nq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nq *NetbirdQuery) Unique(unique bool) *NetbirdQuery {
	nq.ctx.Unique = &unique
	return nq
}

// Order specifies how the records should be ordered.
func (nq *NetbirdQuery) Order(o ...netbird.OrderOption) *NetbirdQuery {
	nq.order = append(nq.order, o...)
	return nq
}

// QueryOwner chains the current query on the "owner" edge.
func (nq *NetbirdQuery) QueryOwner() *AgentQuery {
	query := (&AgentClient{config: nq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := nq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := nq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(netbird.Table, netbird.FieldID, selector),
			sqlgraph.To(agent.Table, agent.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, netbird.OwnerTable, netbird.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(nq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Netbird entity from the query.
// Returns a *NotFoundError when no Netbird was found.
func (nq *NetbirdQuery) First(ctx context.Context) (*Netbird, error) {
	nodes, err := nq.Limit(1).All(setContextOp(ctx, nq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{netbird.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nq *NetbirdQuery) FirstX(ctx context.Context) *Netbird {
	node, err := nq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Netbird ID from the query.
// Returns a *NotFoundError when no Netbird ID was found.
func (nq *NetbirdQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nq.Limit(1).IDs(setContextOp(ctx, nq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{netbird.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nq *NetbirdQuery) FirstIDX(ctx context.Context) int {
	id, err := nq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Netbird entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Netbird entity is found.
// Returns a *NotFoundError when no Netbird entities are found.
func (nq *NetbirdQuery) Only(ctx context.Context) (*Netbird, error) {
	nodes, err := nq.Limit(2).All(setContextOp(ctx, nq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{netbird.Label}
	default:
		return nil, &NotSingularError{netbird.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nq *NetbirdQuery) OnlyX(ctx context.Context) *Netbird {
	node, err := nq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Netbird ID in the query.
// Returns a *NotSingularError when more than one Netbird ID is found.
// Returns a *NotFoundError when no entities are found.
func (nq *NetbirdQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nq.Limit(2).IDs(setContextOp(ctx, nq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{netbird.Label}
	default:
		err = &NotSingularError{netbird.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nq *NetbirdQuery) OnlyIDX(ctx context.Context) int {
	id, err := nq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Netbirds.
func (nq *NetbirdQuery) All(ctx context.Context) ([]*Netbird, error) {
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryAll)
	if err := nq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Netbird, *NetbirdQuery]()
	return withInterceptors[[]*Netbird](ctx, nq, qr, nq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nq *NetbirdQuery) AllX(ctx context.Context) []*Netbird {
	nodes, err := nq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Netbird IDs.
func (nq *NetbirdQuery) IDs(ctx context.Context) (ids []int, err error) {
	if nq.ctx.Unique == nil && nq.path != nil {
		nq.Unique(true)
	}
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryIDs)
	if err = nq.Select(netbird.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nq *NetbirdQuery) IDsX(ctx context.Context) []int {
	ids, err := nq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nq *NetbirdQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryCount)
	if err := nq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nq, querierCount[*NetbirdQuery](), nq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nq *NetbirdQuery) CountX(ctx context.Context) int {
	count, err := nq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nq *NetbirdQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nq.ctx, ent.OpQueryExist)
	switch _, err := nq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nq *NetbirdQuery) ExistX(ctx context.Context) bool {
	exist, err := nq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NetbirdQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nq *NetbirdQuery) Clone() *NetbirdQuery {
	if nq == nil {
		return nil
	}
	return &NetbirdQuery{
		config:     nq.config,
		ctx:        nq.ctx.Clone(),
		order:      append([]netbird.OrderOption{}, nq.order...),
		inters:     append([]Interceptor{}, nq.inters...),
		predicates: append([]predicate.Netbird{}, nq.predicates...),
		withOwner:  nq.withOwner.Clone(),
		// clone intermediate query.
		sql:       nq.sql.Clone(),
		path:      nq.path,
		modifiers: append([]func(*sql.Selector){}, nq.modifiers...),
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (nq *NetbirdQuery) WithOwner(opts ...func(*AgentQuery)) *NetbirdQuery {
	query := (&AgentClient{config: nq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	nq.withOwner = query
	return nq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Version string `json:"version,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Netbird.Query().
//		GroupBy(netbird.FieldVersion).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (nq *NetbirdQuery) GroupBy(field string, fields ...string) *NetbirdGroupBy {
	nq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NetbirdGroupBy{build: nq}
	grbuild.flds = &nq.ctx.Fields
	grbuild.label = netbird.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Version string `json:"version,omitempty"`
//	}
//
//	client.Netbird.Query().
//		Select(netbird.FieldVersion).
//		Scan(ctx, &v)
func (nq *NetbirdQuery) Select(fields ...string) *NetbirdSelect {
	nq.ctx.Fields = append(nq.ctx.Fields, fields...)
	sbuild := &NetbirdSelect{NetbirdQuery: nq}
	sbuild.label = netbird.Label
	sbuild.flds, sbuild.scan = &nq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NetbirdSelect configured with the given aggregations.
func (nq *NetbirdQuery) Aggregate(fns ...AggregateFunc) *NetbirdSelect {
	return nq.Select().Aggregate(fns...)
}

func (nq *NetbirdQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nq); err != nil {
				return err
			}
		}
	}
	for _, f := range nq.ctx.Fields {
		if !netbird.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nq.path != nil {
		prev, err := nq.path(ctx)
		if err != nil {
			return err
		}
		nq.sql = prev
	}
	return nil
}

func (nq *NetbirdQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Netbird, error) {
	var (
		nodes       = []*Netbird{}
		withFKs     = nq.withFKs
		_spec       = nq.querySpec()
		loadedTypes = [1]bool{
			nq.withOwner != nil,
		}
	)
	if nq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, netbird.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Netbird).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Netbird{config: nq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(nq.modifiers) > 0 {
		_spec.Modifiers = nq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := nq.withOwner; query != nil {
		if err := nq.loadOwner(ctx, query, nodes, nil,
			func(n *Netbird, e *Agent) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (nq *NetbirdQuery) loadOwner(ctx context.Context, query *AgentQuery, nodes []*Netbird, init func(*Netbird), assign func(*Netbird, *Agent)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Netbird)
	for i := range nodes {
		if nodes[i].agent_netbird == nil {
			continue
		}
		fk := *nodes[i].agent_netbird
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(agent.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "agent_netbird" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (nq *NetbirdQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nq.querySpec()
	if len(nq.modifiers) > 0 {
		_spec.Modifiers = nq.modifiers
	}
	_spec.Node.Columns = nq.ctx.Fields
	if len(nq.ctx.Fields) > 0 {
		_spec.Unique = nq.ctx.Unique != nil && *nq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nq.driver, _spec)
}

func (nq *NetbirdQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(netbird.Table, netbird.Columns, sqlgraph.NewFieldSpec(netbird.FieldID, field.TypeInt))
	_spec.From = nq.sql
	if unique := nq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nq.path != nil {
		_spec.Unique = true
	}
	if fields := nq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, netbird.FieldID)
		for i := range fields {
			if fields[i] != netbird.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nq *NetbirdQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nq.driver.Dialect())
	t1 := builder.Table(netbird.Table)
	columns := nq.ctx.Fields
	if len(columns) == 0 {
		columns = netbird.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nq.sql != nil {
		selector = nq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nq.ctx.Unique != nil && *nq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range nq.modifiers {
		m(selector)
	}
	for _, p := range nq.predicates {
		p(selector)
	}
	for _, p := range nq.order {
		p(selector)
	}
	if offset := nq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nq *NetbirdQuery) Modify(modifiers ...func(s *sql.Selector)) *NetbirdSelect {
	nq.modifiers = append(nq.modifiers, modifiers...)
	return nq.Select()
}

// NetbirdGroupBy is the group-by builder for Netbird entities.
type NetbirdGroupBy struct {
	selector
	build *NetbirdQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ngb *NetbirdGroupBy) Aggregate(fns ...AggregateFunc) *NetbirdGroupBy {
	ngb.fns = append(ngb.fns, fns...)
	return ngb
}

// Scan applies the selector query and scans the result into the given value.
func (ngb *NetbirdGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ngb.build.ctx, ent.OpQueryGroupBy)
	if err := ngb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NetbirdQuery, *NetbirdGroupBy](ctx, ngb.build, ngb, ngb.build.inters, v)
}

func (ngb *NetbirdGroupBy) sqlScan(ctx context.Context, root *NetbirdQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ngb.fns))
	for _, fn := range ngb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ngb.flds)+len(ngb.fns))
		for _, f := range *ngb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ngb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ngb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NetbirdSelect is the builder for selecting fields of Netbird entities.
type NetbirdSelect struct {
	*NetbirdQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ns *NetbirdSelect) Aggregate(fns ...AggregateFunc) *NetbirdSelect {
	ns.fns = append(ns.fns, fns...)
	return ns
}

// Scan applies the selector query and scans the result into the given value.
func (ns *NetbirdSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ns.ctx, ent.OpQuerySelect)
	if err := ns.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NetbirdQuery, *NetbirdSelect](ctx, ns.NetbirdQuery, ns, ns.inters, v)
}

func (ns *NetbirdSelect) sqlScan(ctx context.Context, root *NetbirdQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ns.fns))
	for _, fn := range ns.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ns.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ns.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ns *NetbirdSelect) Modify(modifiers ...func(s *sql.Selector)) *NetbirdSelect {
	ns.modifiers = append(ns.modifiers, modifiers...)
	return ns
}
