// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/netbirdsettings"
	"github.com/open-uem/ent/predicate"
)

// NetbirdSettingsDelete is the builder for deleting a NetbirdSettings entity.
type NetbirdSettingsDelete struct {
	config
	hooks    []Hook
	mutation *NetbirdSettingsMutation
}

// Where appends a list predicates to the NetbirdSettingsDelete builder.
func (nsd *NetbirdSettingsDelete) Where(ps ...predicate.NetbirdSettings) *NetbirdSettingsDelete {
	nsd.mutation.Where(ps...)
	return nsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nsd *NetbirdSettingsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, nsd.sqlExec, nsd.mutation, nsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (nsd *NetbirdSettingsDelete) ExecX(ctx context.Context) int {
	n, err := nsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nsd *NetbirdSettingsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(netbirdsettings.Table, sqlgraph.NewFieldSpec(netbirdsettings.FieldID, field.TypeInt))
	if ps := nsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, nsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	nsd.mutation.done = true
	return affected, err
}

// NetbirdSettingsDeleteOne is the builder for deleting a single NetbirdSettings entity.
type NetbirdSettingsDeleteOne struct {
	nsd *NetbirdSettingsDelete
}

// Where appends a list predicates to the NetbirdSettingsDelete builder.
func (nsdo *NetbirdSettingsDeleteOne) Where(ps ...predicate.NetbirdSettings) *NetbirdSettingsDeleteOne {
	nsdo.nsd.mutation.Where(ps...)
	return nsdo
}

// Exec executes the deletion query.
func (nsdo *NetbirdSettingsDeleteOne) Exec(ctx context.Context) error {
	n, err := nsdo.nsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{netbirdsettings.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nsdo *NetbirdSettingsDeleteOne) ExecX(ctx context.Context) {
	if err := nsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
