// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/netbirdsettings"
	"github.com/open-uem/ent/predicate"
	"github.com/open-uem/ent/tenant"
)

// NetbirdSettingsQuery is the builder for querying NetbirdSettings entities.
type NetbirdSettingsQuery struct {
	config
	ctx        *QueryContext
	order      []netbirdsettings.OrderOption
	inters     []Interceptor
	predicates []predicate.NetbirdSettings
	withTenant *TenantQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NetbirdSettingsQuery builder.
func (nsq *NetbirdSettingsQuery) Where(ps ...predicate.NetbirdSettings) *NetbirdSettingsQuery {
	nsq.predicates = append(nsq.predicates, ps...)
	return nsq
}

// Limit the number of records to be returned by this query.
func (nsq *NetbirdSettingsQuery) Limit(limit int) *NetbirdSettingsQuery {
	nsq.ctx.Limit = &limit
	return nsq
}

// Offset to start from.
func (nsq *NetbirdSettingsQuery) Offset(offset int) *NetbirdSettingsQuery {
	nsq.ctx.Offset = &offset
	return nsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nsq *NetbirdSettingsQuery) Unique(unique bool) *NetbirdSettingsQuery {
	nsq.ctx.Unique = &unique
	return nsq
}

// Order specifies how the records should be ordered.
func (nsq *NetbirdSettingsQuery) Order(o ...netbirdsettings.OrderOption) *NetbirdSettingsQuery {
	nsq.order = append(nsq.order, o...)
	return nsq
}

// QueryTenant chains the current query on the "tenant" edge.
func (nsq *NetbirdSettingsQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: nsq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := nsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := nsq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(netbirdsettings.Table, netbirdsettings.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, netbirdsettings.TenantTable, netbirdsettings.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(nsq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first NetbirdSettings entity from the query.
// Returns a *NotFoundError when no NetbirdSettings was found.
func (nsq *NetbirdSettingsQuery) First(ctx context.Context) (*NetbirdSettings, error) {
	nodes, err := nsq.Limit(1).All(setContextOp(ctx, nsq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{netbirdsettings.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nsq *NetbirdSettingsQuery) FirstX(ctx context.Context) *NetbirdSettings {
	node, err := nsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NetbirdSettings ID from the query.
// Returns a *NotFoundError when no NetbirdSettings ID was found.
func (nsq *NetbirdSettingsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nsq.Limit(1).IDs(setContextOp(ctx, nsq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{netbirdsettings.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nsq *NetbirdSettingsQuery) FirstIDX(ctx context.Context) int {
	id, err := nsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NetbirdSettings entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NetbirdSettings entity is found.
// Returns a *NotFoundError when no NetbirdSettings entities are found.
func (nsq *NetbirdSettingsQuery) Only(ctx context.Context) (*NetbirdSettings, error) {
	nodes, err := nsq.Limit(2).All(setContextOp(ctx, nsq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{netbirdsettings.Label}
	default:
		return nil, &NotSingularError{netbirdsettings.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nsq *NetbirdSettingsQuery) OnlyX(ctx context.Context) *NetbirdSettings {
	node, err := nsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NetbirdSettings ID in the query.
// Returns a *NotSingularError when more than one NetbirdSettings ID is found.
// Returns a *NotFoundError when no entities are found.
func (nsq *NetbirdSettingsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nsq.Limit(2).IDs(setContextOp(ctx, nsq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{netbirdsettings.Label}
	default:
		err = &NotSingularError{netbirdsettings.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nsq *NetbirdSettingsQuery) OnlyIDX(ctx context.Context) int {
	id, err := nsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NetbirdSettingsSlice.
func (nsq *NetbirdSettingsQuery) All(ctx context.Context) ([]*NetbirdSettings, error) {
	ctx = setContextOp(ctx, nsq.ctx, ent.OpQueryAll)
	if err := nsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NetbirdSettings, *NetbirdSettingsQuery]()
	return withInterceptors[[]*NetbirdSettings](ctx, nsq, qr, nsq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nsq *NetbirdSettingsQuery) AllX(ctx context.Context) []*NetbirdSettings {
	nodes, err := nsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NetbirdSettings IDs.
func (nsq *NetbirdSettingsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if nsq.ctx.Unique == nil && nsq.path != nil {
		nsq.Unique(true)
	}
	ctx = setContextOp(ctx, nsq.ctx, ent.OpQueryIDs)
	if err = nsq.Select(netbirdsettings.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nsq *NetbirdSettingsQuery) IDsX(ctx context.Context) []int {
	ids, err := nsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nsq *NetbirdSettingsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nsq.ctx, ent.OpQueryCount)
	if err := nsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nsq, querierCount[*NetbirdSettingsQuery](), nsq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nsq *NetbirdSettingsQuery) CountX(ctx context.Context) int {
	count, err := nsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nsq *NetbirdSettingsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nsq.ctx, ent.OpQueryExist)
	switch _, err := nsq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nsq *NetbirdSettingsQuery) ExistX(ctx context.Context) bool {
	exist, err := nsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NetbirdSettingsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nsq *NetbirdSettingsQuery) Clone() *NetbirdSettingsQuery {
	if nsq == nil {
		return nil
	}
	return &NetbirdSettingsQuery{
		config:     nsq.config,
		ctx:        nsq.ctx.Clone(),
		order:      append([]netbirdsettings.OrderOption{}, nsq.order...),
		inters:     append([]Interceptor{}, nsq.inters...),
		predicates: append([]predicate.NetbirdSettings{}, nsq.predicates...),
		withTenant: nsq.withTenant.Clone(),
		// clone intermediate query.
		sql:       nsq.sql.Clone(),
		path:      nsq.path,
		modifiers: append([]func(*sql.Selector){}, nsq.modifiers...),
	}
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (nsq *NetbirdSettingsQuery) WithTenant(opts ...func(*TenantQuery)) *NetbirdSettingsQuery {
	query := (&TenantClient{config: nsq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	nsq.withTenant = query
	return nsq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ManagementURL string `json:"management_url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NetbirdSettings.Query().
//		GroupBy(netbirdsettings.FieldManagementURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (nsq *NetbirdSettingsQuery) GroupBy(field string, fields ...string) *NetbirdSettingsGroupBy {
	nsq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NetbirdSettingsGroupBy{build: nsq}
	grbuild.flds = &nsq.ctx.Fields
	grbuild.label = netbirdsettings.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ManagementURL string `json:"management_url,omitempty"`
//	}
//
//	client.NetbirdSettings.Query().
//		Select(netbirdsettings.FieldManagementURL).
//		Scan(ctx, &v)
func (nsq *NetbirdSettingsQuery) Select(fields ...string) *NetbirdSettingsSelect {
	nsq.ctx.Fields = append(nsq.ctx.Fields, fields...)
	sbuild := &NetbirdSettingsSelect{NetbirdSettingsQuery: nsq}
	sbuild.label = netbirdsettings.Label
	sbuild.flds, sbuild.scan = &nsq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NetbirdSettingsSelect configured with the given aggregations.
func (nsq *NetbirdSettingsQuery) Aggregate(fns ...AggregateFunc) *NetbirdSettingsSelect {
	return nsq.Select().Aggregate(fns...)
}

func (nsq *NetbirdSettingsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nsq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nsq); err != nil {
				return err
			}
		}
	}
	for _, f := range nsq.ctx.Fields {
		if !netbirdsettings.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nsq.path != nil {
		prev, err := nsq.path(ctx)
		if err != nil {
			return err
		}
		nsq.sql = prev
	}
	return nil
}

func (nsq *NetbirdSettingsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NetbirdSettings, error) {
	var (
		nodes       = []*NetbirdSettings{}
		_spec       = nsq.querySpec()
		loadedTypes = [1]bool{
			nsq.withTenant != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NetbirdSettings).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NetbirdSettings{config: nsq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(nsq.modifiers) > 0 {
		_spec.Modifiers = nsq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := nsq.withTenant; query != nil {
		if err := nsq.loadTenant(ctx, query, nodes,
			func(n *NetbirdSettings) { n.Edges.Tenant = []*Tenant{} },
			func(n *NetbirdSettings, e *Tenant) { n.Edges.Tenant = append(n.Edges.Tenant, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (nsq *NetbirdSettingsQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*NetbirdSettings, init func(*NetbirdSettings), assign func(*NetbirdSettings, *Tenant)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*NetbirdSettings)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Tenant(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(netbirdsettings.TenantColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.tenant_netbird
		if fk == nil {
			return fmt.Errorf(`foreign-key "tenant_netbird" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tenant_netbird" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (nsq *NetbirdSettingsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nsq.querySpec()
	if len(nsq.modifiers) > 0 {
		_spec.Modifiers = nsq.modifiers
	}
	_spec.Node.Columns = nsq.ctx.Fields
	if len(nsq.ctx.Fields) > 0 {
		_spec.Unique = nsq.ctx.Unique != nil && *nsq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nsq.driver, _spec)
}

func (nsq *NetbirdSettingsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(netbirdsettings.Table, netbirdsettings.Columns, sqlgraph.NewFieldSpec(netbirdsettings.FieldID, field.TypeInt))
	_spec.From = nsq.sql
	if unique := nsq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nsq.path != nil {
		_spec.Unique = true
	}
	if fields := nsq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, netbirdsettings.FieldID)
		for i := range fields {
			if fields[i] != netbirdsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nsq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nsq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nsq *NetbirdSettingsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nsq.driver.Dialect())
	t1 := builder.Table(netbirdsettings.Table)
	columns := nsq.ctx.Fields
	if len(columns) == 0 {
		columns = netbirdsettings.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nsq.sql != nil {
		selector = nsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nsq.ctx.Unique != nil && *nsq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range nsq.modifiers {
		m(selector)
	}
	for _, p := range nsq.predicates {
		p(selector)
	}
	for _, p := range nsq.order {
		p(selector)
	}
	if offset := nsq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nsq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nsq *NetbirdSettingsQuery) Modify(modifiers ...func(s *sql.Selector)) *NetbirdSettingsSelect {
	nsq.modifiers = append(nsq.modifiers, modifiers...)
	return nsq.Select()
}

// NetbirdSettingsGroupBy is the group-by builder for NetbirdSettings entities.
type NetbirdSettingsGroupBy struct {
	selector
	build *NetbirdSettingsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nsgb *NetbirdSettingsGroupBy) Aggregate(fns ...AggregateFunc) *NetbirdSettingsGroupBy {
	nsgb.fns = append(nsgb.fns, fns...)
	return nsgb
}

// Scan applies the selector query and scans the result into the given value.
func (nsgb *NetbirdSettingsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nsgb.build.ctx, ent.OpQueryGroupBy)
	if err := nsgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NetbirdSettingsQuery, *NetbirdSettingsGroupBy](ctx, nsgb.build, nsgb, nsgb.build.inters, v)
}

func (nsgb *NetbirdSettingsGroupBy) sqlScan(ctx context.Context, root *NetbirdSettingsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(nsgb.fns))
	for _, fn := range nsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*nsgb.flds)+len(nsgb.fns))
		for _, f := range *nsgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*nsgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nsgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NetbirdSettingsSelect is the builder for selecting fields of NetbirdSettings entities.
type NetbirdSettingsSelect struct {
	*NetbirdSettingsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (nss *NetbirdSettingsSelect) Aggregate(fns ...AggregateFunc) *NetbirdSettingsSelect {
	nss.fns = append(nss.fns, fns...)
	return nss
}

// Scan applies the selector query and scans the result into the given value.
func (nss *NetbirdSettingsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nss.ctx, ent.OpQuerySelect)
	if err := nss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NetbirdSettingsQuery, *NetbirdSettingsSelect](ctx, nss.NetbirdSettingsQuery, nss, nss.inters, v)
}

func (nss *NetbirdSettingsSelect) sqlScan(ctx context.Context, root *NetbirdSettingsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(nss.fns))
	for _, fn := range nss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*nss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (nss *NetbirdSettingsSelect) Modify(modifiers ...func(s *sql.Selector)) *NetbirdSettingsSelect {
	nss.modifiers = append(nss.modifiers, modifiers...)
	return nss
}
