// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/netbirdsettings"
	"github.com/open-uem/ent/predicate"
	"github.com/open-uem/ent/tenant"
)

// NetbirdSettingsUpdate is the builder for updating NetbirdSettings entities.
type NetbirdSettingsUpdate struct {
	config
	hooks     []Hook
	mutation  *NetbirdSettingsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NetbirdSettingsUpdate builder.
func (nsu *NetbirdSettingsUpdate) Where(ps ...predicate.NetbirdSettings) *NetbirdSettingsUpdate {
	nsu.mutation.Where(ps...)
	return nsu
}

// SetManagementURL sets the "management_url" field.
func (nsu *NetbirdSettingsUpdate) SetManagementURL(s string) *NetbirdSettingsUpdate {
	nsu.mutation.SetManagementURL(s)
	return nsu
}

// SetNillableManagementURL sets the "management_url" field if the given value is not nil.
func (nsu *NetbirdSettingsUpdate) SetNillableManagementURL(s *string) *NetbirdSettingsUpdate {
	if s != nil {
		nsu.SetManagementURL(*s)
	}
	return nsu
}

// ClearManagementURL clears the value of the "management_url" field.
func (nsu *NetbirdSettingsUpdate) ClearManagementURL() *NetbirdSettingsUpdate {
	nsu.mutation.ClearManagementURL()
	return nsu
}

// SetAccessToken sets the "access_token" field.
func (nsu *NetbirdSettingsUpdate) SetAccessToken(s string) *NetbirdSettingsUpdate {
	nsu.mutation.SetAccessToken(s)
	return nsu
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (nsu *NetbirdSettingsUpdate) SetNillableAccessToken(s *string) *NetbirdSettingsUpdate {
	if s != nil {
		nsu.SetAccessToken(*s)
	}
	return nsu
}

// ClearAccessToken clears the value of the "access_token" field.
func (nsu *NetbirdSettingsUpdate) ClearAccessToken() *NetbirdSettingsUpdate {
	nsu.mutation.ClearAccessToken()
	return nsu
}

// AddTenantIDs adds the "tenant" edge to the Tenant entity by IDs.
func (nsu *NetbirdSettingsUpdate) AddTenantIDs(ids ...int) *NetbirdSettingsUpdate {
	nsu.mutation.AddTenantIDs(ids...)
	return nsu
}

// AddTenant adds the "tenant" edges to the Tenant entity.
func (nsu *NetbirdSettingsUpdate) AddTenant(t ...*Tenant) *NetbirdSettingsUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return nsu.AddTenantIDs(ids...)
}

// Mutation returns the NetbirdSettingsMutation object of the builder.
func (nsu *NetbirdSettingsUpdate) Mutation() *NetbirdSettingsMutation {
	return nsu.mutation
}

// ClearTenant clears all "tenant" edges to the Tenant entity.
func (nsu *NetbirdSettingsUpdate) ClearTenant() *NetbirdSettingsUpdate {
	nsu.mutation.ClearTenant()
	return nsu
}

// RemoveTenantIDs removes the "tenant" edge to Tenant entities by IDs.
func (nsu *NetbirdSettingsUpdate) RemoveTenantIDs(ids ...int) *NetbirdSettingsUpdate {
	nsu.mutation.RemoveTenantIDs(ids...)
	return nsu
}

// RemoveTenant removes "tenant" edges to Tenant entities.
func (nsu *NetbirdSettingsUpdate) RemoveTenant(t ...*Tenant) *NetbirdSettingsUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return nsu.RemoveTenantIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nsu *NetbirdSettingsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, nsu.sqlSave, nsu.mutation, nsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nsu *NetbirdSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := nsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nsu *NetbirdSettingsUpdate) Exec(ctx context.Context) error {
	_, err := nsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nsu *NetbirdSettingsUpdate) ExecX(ctx context.Context) {
	if err := nsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (nsu *NetbirdSettingsUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NetbirdSettingsUpdate {
	nsu.modifiers = append(nsu.modifiers, modifiers...)
	return nsu
}

func (nsu *NetbirdSettingsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(netbirdsettings.Table, netbirdsettings.Columns, sqlgraph.NewFieldSpec(netbirdsettings.FieldID, field.TypeInt))
	if ps := nsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nsu.mutation.ManagementURL(); ok {
		_spec.SetField(netbirdsettings.FieldManagementURL, field.TypeString, value)
	}
	if nsu.mutation.ManagementURLCleared() {
		_spec.ClearField(netbirdsettings.FieldManagementURL, field.TypeString)
	}
	if value, ok := nsu.mutation.AccessToken(); ok {
		_spec.SetField(netbirdsettings.FieldAccessToken, field.TypeString, value)
	}
	if nsu.mutation.AccessTokenCleared() {
		_spec.ClearField(netbirdsettings.FieldAccessToken, field.TypeString)
	}
	if nsu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   netbirdsettings.TenantTable,
			Columns: []string{netbirdsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nsu.mutation.RemovedTenantIDs(); len(nodes) > 0 && !nsu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   netbirdsettings.TenantTable,
			Columns: []string{netbirdsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nsu.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   netbirdsettings.TenantTable,
			Columns: []string{netbirdsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(nsu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, nsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{netbirdsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nsu.mutation.done = true
	return n, nil
}

// NetbirdSettingsUpdateOne is the builder for updating a single NetbirdSettings entity.
type NetbirdSettingsUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NetbirdSettingsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetManagementURL sets the "management_url" field.
func (nsuo *NetbirdSettingsUpdateOne) SetManagementURL(s string) *NetbirdSettingsUpdateOne {
	nsuo.mutation.SetManagementURL(s)
	return nsuo
}

// SetNillableManagementURL sets the "management_url" field if the given value is not nil.
func (nsuo *NetbirdSettingsUpdateOne) SetNillableManagementURL(s *string) *NetbirdSettingsUpdateOne {
	if s != nil {
		nsuo.SetManagementURL(*s)
	}
	return nsuo
}

// ClearManagementURL clears the value of the "management_url" field.
func (nsuo *NetbirdSettingsUpdateOne) ClearManagementURL() *NetbirdSettingsUpdateOne {
	nsuo.mutation.ClearManagementURL()
	return nsuo
}

// SetAccessToken sets the "access_token" field.
func (nsuo *NetbirdSettingsUpdateOne) SetAccessToken(s string) *NetbirdSettingsUpdateOne {
	nsuo.mutation.SetAccessToken(s)
	return nsuo
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (nsuo *NetbirdSettingsUpdateOne) SetNillableAccessToken(s *string) *NetbirdSettingsUpdateOne {
	if s != nil {
		nsuo.SetAccessToken(*s)
	}
	return nsuo
}

// ClearAccessToken clears the value of the "access_token" field.
func (nsuo *NetbirdSettingsUpdateOne) ClearAccessToken() *NetbirdSettingsUpdateOne {
	nsuo.mutation.ClearAccessToken()
	return nsuo
}

// AddTenantIDs adds the "tenant" edge to the Tenant entity by IDs.
func (nsuo *NetbirdSettingsUpdateOne) AddTenantIDs(ids ...int) *NetbirdSettingsUpdateOne {
	nsuo.mutation.AddTenantIDs(ids...)
	return nsuo
}

// AddTenant adds the "tenant" edges to the Tenant entity.
func (nsuo *NetbirdSettingsUpdateOne) AddTenant(t ...*Tenant) *NetbirdSettingsUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return nsuo.AddTenantIDs(ids...)
}

// Mutation returns the NetbirdSettingsMutation object of the builder.
func (nsuo *NetbirdSettingsUpdateOne) Mutation() *NetbirdSettingsMutation {
	return nsuo.mutation
}

// ClearTenant clears all "tenant" edges to the Tenant entity.
func (nsuo *NetbirdSettingsUpdateOne) ClearTenant() *NetbirdSettingsUpdateOne {
	nsuo.mutation.ClearTenant()
	return nsuo
}

// RemoveTenantIDs removes the "tenant" edge to Tenant entities by IDs.
func (nsuo *NetbirdSettingsUpdateOne) RemoveTenantIDs(ids ...int) *NetbirdSettingsUpdateOne {
	nsuo.mutation.RemoveTenantIDs(ids...)
	return nsuo
}

// RemoveTenant removes "tenant" edges to Tenant entities.
func (nsuo *NetbirdSettingsUpdateOne) RemoveTenant(t ...*Tenant) *NetbirdSettingsUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return nsuo.RemoveTenantIDs(ids...)
}

// Where appends a list predicates to the NetbirdSettingsUpdate builder.
func (nsuo *NetbirdSettingsUpdateOne) Where(ps ...predicate.NetbirdSettings) *NetbirdSettingsUpdateOne {
	nsuo.mutation.Where(ps...)
	return nsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nsuo *NetbirdSettingsUpdateOne) Select(field string, fields ...string) *NetbirdSettingsUpdateOne {
	nsuo.fields = append([]string{field}, fields...)
	return nsuo
}

// Save executes the query and returns the updated NetbirdSettings entity.
func (nsuo *NetbirdSettingsUpdateOne) Save(ctx context.Context) (*NetbirdSettings, error) {
	return withHooks(ctx, nsuo.sqlSave, nsuo.mutation, nsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nsuo *NetbirdSettingsUpdateOne) SaveX(ctx context.Context) *NetbirdSettings {
	node, err := nsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nsuo *NetbirdSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := nsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nsuo *NetbirdSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := nsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (nsuo *NetbirdSettingsUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NetbirdSettingsUpdateOne {
	nsuo.modifiers = append(nsuo.modifiers, modifiers...)
	return nsuo
}

func (nsuo *NetbirdSettingsUpdateOne) sqlSave(ctx context.Context) (_node *NetbirdSettings, err error) {
	_spec := sqlgraph.NewUpdateSpec(netbirdsettings.Table, netbirdsettings.Columns, sqlgraph.NewFieldSpec(netbirdsettings.FieldID, field.TypeInt))
	id, ok := nsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NetbirdSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, netbirdsettings.FieldID)
		for _, f := range fields {
			if !netbirdsettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != netbirdsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nsuo.mutation.ManagementURL(); ok {
		_spec.SetField(netbirdsettings.FieldManagementURL, field.TypeString, value)
	}
	if nsuo.mutation.ManagementURLCleared() {
		_spec.ClearField(netbirdsettings.FieldManagementURL, field.TypeString)
	}
	if value, ok := nsuo.mutation.AccessToken(); ok {
		_spec.SetField(netbirdsettings.FieldAccessToken, field.TypeString, value)
	}
	if nsuo.mutation.AccessTokenCleared() {
		_spec.ClearField(netbirdsettings.FieldAccessToken, field.TypeString)
	}
	if nsuo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   netbirdsettings.TenantTable,
			Columns: []string{netbirdsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nsuo.mutation.RemovedTenantIDs(); len(nodes) > 0 && !nsuo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   netbirdsettings.TenantTable,
			Columns: []string{netbirdsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nsuo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   netbirdsettings.TenantTable,
			Columns: []string{netbirdsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(nsuo.modifiers...)
	_node = &NetbirdSettings{config: nsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{netbirdsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nsuo.mutation.done = true
	return _node, nil
}
