// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/open-uem/ent/netbirdsettings"
	"github.com/open-uem/ent/tenant"
)

// NetbirdSettingsCreate is the builder for creating a NetbirdSettings entity.
type NetbirdSettingsCreate struct {
	config
	mutation *NetbirdSettingsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetManagementURL sets the "management_url" field.
func (nsc *NetbirdSettingsCreate) SetManagementURL(s string) *NetbirdSettingsCreate {
	nsc.mutation.SetManagementURL(s)
	return nsc
}

// SetNillableManagementURL sets the "management_url" field if the given value is not nil.
func (nsc *NetbirdSettingsCreate) SetNillableManagementURL(s *string) *NetbirdSettingsCreate {
	if s != nil {
		nsc.SetManagementURL(*s)
	}
	return nsc
}

// SetAccessToken sets the "access_token" field.
func (nsc *NetbirdSettingsCreate) SetAccessToken(s string) *NetbirdSettingsCreate {
	nsc.mutation.SetAccessToken(s)
	return nsc
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (nsc *NetbirdSettingsCreate) SetNillableAccessToken(s *string) *NetbirdSettingsCreate {
	if s != nil {
		nsc.SetAccessToken(*s)
	}
	return nsc
}

// AddTenantIDs adds the "tenant" edge to the Tenant entity by IDs.
func (nsc *NetbirdSettingsCreate) AddTenantIDs(ids ...int) *NetbirdSettingsCreate {
	nsc.mutation.AddTenantIDs(ids...)
	return nsc
}

// AddTenant adds the "tenant" edges to the Tenant entity.
func (nsc *NetbirdSettingsCreate) AddTenant(t ...*Tenant) *NetbirdSettingsCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return nsc.AddTenantIDs(ids...)
}

// Mutation returns the NetbirdSettingsMutation object of the builder.
func (nsc *NetbirdSettingsCreate) Mutation() *NetbirdSettingsMutation {
	return nsc.mutation
}

// Save creates the NetbirdSettings in the database.
func (nsc *NetbirdSettingsCreate) Save(ctx context.Context) (*NetbirdSettings, error) {
	nsc.defaults()
	return withHooks(ctx, nsc.sqlSave, nsc.mutation, nsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (nsc *NetbirdSettingsCreate) SaveX(ctx context.Context) *NetbirdSettings {
	v, err := nsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nsc *NetbirdSettingsCreate) Exec(ctx context.Context) error {
	_, err := nsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nsc *NetbirdSettingsCreate) ExecX(ctx context.Context) {
	if err := nsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nsc *NetbirdSettingsCreate) defaults() {
	if _, ok := nsc.mutation.ManagementURL(); !ok {
		v := netbirdsettings.DefaultManagementURL
		nsc.mutation.SetManagementURL(v)
	}
	if _, ok := nsc.mutation.AccessToken(); !ok {
		v := netbirdsettings.DefaultAccessToken
		nsc.mutation.SetAccessToken(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nsc *NetbirdSettingsCreate) check() error {
	return nil
}

func (nsc *NetbirdSettingsCreate) sqlSave(ctx context.Context) (*NetbirdSettings, error) {
	if err := nsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := nsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	nsc.mutation.id = &_node.ID
	nsc.mutation.done = true
	return _node, nil
}

func (nsc *NetbirdSettingsCreate) createSpec() (*NetbirdSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &NetbirdSettings{config: nsc.config}
		_spec = sqlgraph.NewCreateSpec(netbirdsettings.Table, sqlgraph.NewFieldSpec(netbirdsettings.FieldID, field.TypeInt))
	)
	_spec.OnConflict = nsc.conflict
	if value, ok := nsc.mutation.ManagementURL(); ok {
		_spec.SetField(netbirdsettings.FieldManagementURL, field.TypeString, value)
		_node.ManagementURL = value
	}
	if value, ok := nsc.mutation.AccessToken(); ok {
		_spec.SetField(netbirdsettings.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if nodes := nsc.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   netbirdsettings.TenantTable,
			Columns: []string{netbirdsettings.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NetbirdSettings.Create().
//		SetManagementURL(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NetbirdSettingsUpsert) {
//			SetManagementURL(v+v).
//		}).
//		Exec(ctx)
func (nsc *NetbirdSettingsCreate) OnConflict(opts ...sql.ConflictOption) *NetbirdSettingsUpsertOne {
	nsc.conflict = opts
	return &NetbirdSettingsUpsertOne{
		create: nsc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NetbirdSettings.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (nsc *NetbirdSettingsCreate) OnConflictColumns(columns ...string) *NetbirdSettingsUpsertOne {
	nsc.conflict = append(nsc.conflict, sql.ConflictColumns(columns...))
	return &NetbirdSettingsUpsertOne{
		create: nsc,
	}
}

type (
	// NetbirdSettingsUpsertOne is the builder for "upsert"-ing
	//  one NetbirdSettings node.
	NetbirdSettingsUpsertOne struct {
		create *NetbirdSettingsCreate
	}

	// NetbirdSettingsUpsert is the "OnConflict" setter.
	NetbirdSettingsUpsert struct {
		*sql.UpdateSet
	}
)

// SetManagementURL sets the "management_url" field.
func (u *NetbirdSettingsUpsert) SetManagementURL(v string) *NetbirdSettingsUpsert {
	u.Set(netbirdsettings.FieldManagementURL, v)
	return u
}

// UpdateManagementURL sets the "management_url" field to the value that was provided on create.
func (u *NetbirdSettingsUpsert) UpdateManagementURL() *NetbirdSettingsUpsert {
	u.SetExcluded(netbirdsettings.FieldManagementURL)
	return u
}

// ClearManagementURL clears the value of the "management_url" field.
func (u *NetbirdSettingsUpsert) ClearManagementURL() *NetbirdSettingsUpsert {
	u.SetNull(netbirdsettings.FieldManagementURL)
	return u
}

// SetAccessToken sets the "access_token" field.
func (u *NetbirdSettingsUpsert) SetAccessToken(v string) *NetbirdSettingsUpsert {
	u.Set(netbirdsettings.FieldAccessToken, v)
	return u
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *NetbirdSettingsUpsert) UpdateAccessToken() *NetbirdSettingsUpsert {
	u.SetExcluded(netbirdsettings.FieldAccessToken)
	return u
}

// ClearAccessToken clears the value of the "access_token" field.
func (u *NetbirdSettingsUpsert) ClearAccessToken() *NetbirdSettingsUpsert {
	u.SetNull(netbirdsettings.FieldAccessToken)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NetbirdSettings.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NetbirdSettingsUpsertOne) UpdateNewValues() *NetbirdSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NetbirdSettings.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NetbirdSettingsUpsertOne) Ignore() *NetbirdSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NetbirdSettingsUpsertOne) DoNothing() *NetbirdSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NetbirdSettingsCreate.OnConflict
// documentation for more info.
func (u *NetbirdSettingsUpsertOne) Update(set func(*NetbirdSettingsUpsert)) *NetbirdSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NetbirdSettingsUpsert{UpdateSet: update})
	}))
	return u
}

// SetManagementURL sets the "management_url" field.
func (u *NetbirdSettingsUpsertOne) SetManagementURL(v string) *NetbirdSettingsUpsertOne {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.SetManagementURL(v)
	})
}

// UpdateManagementURL sets the "management_url" field to the value that was provided on create.
func (u *NetbirdSettingsUpsertOne) UpdateManagementURL() *NetbirdSettingsUpsertOne {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.UpdateManagementURL()
	})
}

// ClearManagementURL clears the value of the "management_url" field.
func (u *NetbirdSettingsUpsertOne) ClearManagementURL() *NetbirdSettingsUpsertOne {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.ClearManagementURL()
	})
}

// SetAccessToken sets the "access_token" field.
func (u *NetbirdSettingsUpsertOne) SetAccessToken(v string) *NetbirdSettingsUpsertOne {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.SetAccessToken(v)
	})
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *NetbirdSettingsUpsertOne) UpdateAccessToken() *NetbirdSettingsUpsertOne {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.UpdateAccessToken()
	})
}

// ClearAccessToken clears the value of the "access_token" field.
func (u *NetbirdSettingsUpsertOne) ClearAccessToken() *NetbirdSettingsUpsertOne {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.ClearAccessToken()
	})
}

// Exec executes the query.
func (u *NetbirdSettingsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NetbirdSettingsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NetbirdSettingsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NetbirdSettingsUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NetbirdSettingsUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NetbirdSettingsCreateBulk is the builder for creating many NetbirdSettings entities in bulk.
type NetbirdSettingsCreateBulk struct {
	config
	err      error
	builders []*NetbirdSettingsCreate
	conflict []sql.ConflictOption
}

// Save creates the NetbirdSettings entities in the database.
func (nscb *NetbirdSettingsCreateBulk) Save(ctx context.Context) ([]*NetbirdSettings, error) {
	if nscb.err != nil {
		return nil, nscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(nscb.builders))
	nodes := make([]*NetbirdSettings, len(nscb.builders))
	mutators := make([]Mutator, len(nscb.builders))
	for i := range nscb.builders {
		func(i int, root context.Context) {
			builder := nscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NetbirdSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, nscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = nscb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, nscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, nscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (nscb *NetbirdSettingsCreateBulk) SaveX(ctx context.Context) []*NetbirdSettings {
	v, err := nscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nscb *NetbirdSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := nscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nscb *NetbirdSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := nscb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NetbirdSettings.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NetbirdSettingsUpsert) {
//			SetManagementURL(v+v).
//		}).
//		Exec(ctx)
func (nscb *NetbirdSettingsCreateBulk) OnConflict(opts ...sql.ConflictOption) *NetbirdSettingsUpsertBulk {
	nscb.conflict = opts
	return &NetbirdSettingsUpsertBulk{
		create: nscb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NetbirdSettings.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (nscb *NetbirdSettingsCreateBulk) OnConflictColumns(columns ...string) *NetbirdSettingsUpsertBulk {
	nscb.conflict = append(nscb.conflict, sql.ConflictColumns(columns...))
	return &NetbirdSettingsUpsertBulk{
		create: nscb,
	}
}

// NetbirdSettingsUpsertBulk is the builder for "upsert"-ing
// a bulk of NetbirdSettings nodes.
type NetbirdSettingsUpsertBulk struct {
	create *NetbirdSettingsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NetbirdSettings.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NetbirdSettingsUpsertBulk) UpdateNewValues() *NetbirdSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NetbirdSettings.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NetbirdSettingsUpsertBulk) Ignore() *NetbirdSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NetbirdSettingsUpsertBulk) DoNothing() *NetbirdSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NetbirdSettingsCreateBulk.OnConflict
// documentation for more info.
func (u *NetbirdSettingsUpsertBulk) Update(set func(*NetbirdSettingsUpsert)) *NetbirdSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NetbirdSettingsUpsert{UpdateSet: update})
	}))
	return u
}

// SetManagementURL sets the "management_url" field.
func (u *NetbirdSettingsUpsertBulk) SetManagementURL(v string) *NetbirdSettingsUpsertBulk {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.SetManagementURL(v)
	})
}

// UpdateManagementURL sets the "management_url" field to the value that was provided on create.
func (u *NetbirdSettingsUpsertBulk) UpdateManagementURL() *NetbirdSettingsUpsertBulk {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.UpdateManagementURL()
	})
}

// ClearManagementURL clears the value of the "management_url" field.
func (u *NetbirdSettingsUpsertBulk) ClearManagementURL() *NetbirdSettingsUpsertBulk {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.ClearManagementURL()
	})
}

// SetAccessToken sets the "access_token" field.
func (u *NetbirdSettingsUpsertBulk) SetAccessToken(v string) *NetbirdSettingsUpsertBulk {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.SetAccessToken(v)
	})
}

// UpdateAccessToken sets the "access_token" field to the value that was provided on create.
func (u *NetbirdSettingsUpsertBulk) UpdateAccessToken() *NetbirdSettingsUpsertBulk {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.UpdateAccessToken()
	})
}

// ClearAccessToken clears the value of the "access_token" field.
func (u *NetbirdSettingsUpsertBulk) ClearAccessToken() *NetbirdSettingsUpsertBulk {
	return u.Update(func(s *NetbirdSettingsUpsert) {
		s.ClearAccessToken()
	})
}

// Exec executes the query.
func (u *NetbirdSettingsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NetbirdSettingsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NetbirdSettingsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NetbirdSettingsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
