import React, { useEffect, useMemo, useState } from 'react';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { getRtgsTemplateStatus } from '../api/client';

type BankId = 'icici' | 'kotak' | 'hdfc' | 'sbi';
type Profile = { branch: string; account: string; mobile: string; company: string; address1: string; address2: string; email: string };
type FormState = Profile & { bank: BankId; mode: 'RTGS' | 'NEFT'; payment: 'CHEQUE' | 'CASH'; date: string; cheque: string; amount: string; beneficiaryName: string; beneficiaryAccount: string; ifsc: string; beneficiaryBank: string; beneficiaryBranch: string; beneficiaryAddress: string; beneficiaryContact: string; purpose: string; kotakAccountType: string; hdfcAccountType: string; banv: 'VERIFY' | 'CUSTOMER_VERIFIED'; remitterLei: string; remitterLeiExpiry: string; beneficiaryLei: string; beneficiaryLeiExpiry: string };

const PROFILE_KEY = 'payment_notifier_rtgs_profiles_v1';
const BANKS: Record<BankId, { label: string; asset: string }> = {
  icici: { label: 'ICICI Bank', asset: '/dashboard/rtgs-forms/ICICI-RTGS-NEFT.pdf' },
  kotak: { label: 'Kotak Mahindra Bank', asset: '/dashboard/rtgs-forms/Kotak-RTGS-NEFT.pdf' },
  hdfc: { label: 'HDFC Bank', asset: '/dashboard/rtgs-forms/HDFC-RTGS-NEFT.pdf' },
  sbi: { label: 'State Bank of India', asset: '/dashboard/rtgs-forms/SBI-RTGS-NEFT.pdf' },
};
const blankProfile: Profile = { branch: '', account: '', mobile: '', company: '', address1: '', address2: '', email: '' };
const dateToday = () => new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date()).replace(/\//g, '');
const initialForm = (): FormState => ({ bank: 'icici', mode: 'RTGS', payment: 'CHEQUE', date: dateToday(), cheque: '', amount: '', beneficiaryName: '', beneficiaryAccount: '', ifsc: '', beneficiaryBank: '', beneficiaryBranch: '', beneficiaryAddress: '', beneficiaryContact: '', purpose: '', kotakAccountType: 'CURRENT', hdfcAccountType: 'RESIDENT', banv: 'VERIFY', remitterLei: '', remitterLeiExpiry: '', beneficiaryLei: '', beneficiaryLeiExpiry: '', ...blankProfile });
const upper = (text: string) => text.trim().toUpperCase();
const fieldClass = 'mt-1 w-full rounded-xl border border-gray-300 bg-white px-3 py-2.5 text-sm font-semibold text-gray-900 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100';
const labelClass = 'text-[10px] font-black uppercase tracking-widest text-gray-500';

function readProfiles(): Record<string, Profile> { try { return JSON.parse(localStorage.getItem(PROFILE_KEY) || '{}'); } catch { return {}; } }
function write(page: any, x: number, y: number, text: string, font: any, size = 8, max = 90) { if (text) page.drawText(text.slice(0, max), { x, y, size, font, color: rgb(0, 0, 0) }); }
function comb(page: any, x: number, y: number, width: number, count: number, text: string, font: any, size = 8) { [...text.slice(0, count)].forEach((character, index) => write(page, x + (width / count) * index + 1, y, character, font, size, 1)); }
function mark(page: any, x: number, y: number, font: any) { write(page, x + 1, y + 1, 'X', font, 8, 1); }
const ones = ['', 'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE', 'TEN', 'ELEVEN', 'TWELVE', 'THIRTEEN', 'FOURTEEN', 'FIFTEEN', 'SIXTEEN', 'SEVENTEEN', 'EIGHTEEN', 'NINETEEN'];
const tens = ['', '', 'TWENTY', 'THIRTY', 'FORTY', 'FIFTY', 'SIXTY', 'SEVENTY', 'EIGHTY', 'NINETY'];
function underThousand(value: bigint) { const n = Number(value); if (!n) return ''; const head = n >= 100 ? `${ones[Math.floor(n / 100)]} HUNDRED${n % 100 ? ' ' : ''}` : ''; const tail = n % 100 < 20 ? ones[n % 100] : `${tens[Math.floor((n % 100) / 10)]}${n % 10 ? ` ${ones[n % 10]}` : ''}`; return `${head}${tail}`.trim(); }
function indianWords(number: bigint) { if (number === 0n) return 'ZERO'; const groups: Array<[bigint, string]> = [[10000000n, 'CRORE'], [100000n, 'LAKH'], [1000n, 'THOUSAND'], [1n, '']]; let rest = number; const out: string[] = []; for (const [base, label] of groups) { const part = rest / base; if (part) out.push(`${underThousand(part)}${label ? ` ${label}` : ''}`); rest %= base; } return out.join(' '); }
function parseAmount(raw: string) { const clean = raw.replace(/[,₹]/g, '').trim(); if (!/^\d+(\.\d{1,2})?$/.test(clean)) return null; const [whole, fraction = ''] = clean.split('.'); const paise = Number((fraction + '00').slice(0, 2)); return { whole: BigInt(whole), paise, display: `${Number(whole).toLocaleString('en-IN')}${paise ? `.${String(paise).padStart(2, '0')}` : ''}` }; }
function words(parsed: NonNullable<ReturnType<typeof parseAmount>>) { return `RUPEES ${indianWords(parsed.whole)}${parsed.paise ? ` AND PAISE ${indianWords(BigInt(parsed.paise))}` : ''} ONLY`; }
function split(text: string) { const cut = 54; if (text.length <= cut) return [text, '']; const point = text.lastIndexOf(' ', cut); return [text.slice(0, point), text.slice(point + 1)]; }

function fillIcici(pdf: any, font: any, form: FormState, amount: NonNullable<ReturnType<typeof parseAmount>>) {
  const boxes: Record<string, number[]> = { branch: [0,18,866], date:[0,456,882], figures:[0,212,835], words1:[0,435,835], words2:[0,18,822], account:[0,201,654], cheque:[0,131,475], name:[0,158,450], addr1:[0,158,429], addr2:[0,158,413], mobile:[0,262,389], beneficiary:[0,173,344], beneAccount:[0,173,321], bank:[0,158,244], ifsc:[0,322,224], branchAddress:[0,158,202], ackName:[1,132,101], ackBeneficiary:[1,132,80], ackBank:[1,132,61], ackDate:[1,454,101], ackAccount:[1,421,62], ackAmount:[1,361,43] };
  const pages = pdf.getPages(); const line = (key: string, value: string) => { const [page, x, y] = boxes[key]; write(pages[page], x, y, value, font); };
  const [line1, line2] = split(words(amount)); mark(pages[0], form.mode === 'RTGS' ? 161 : 203, 969, font); mark(pages[0], form.payment === 'CASH' ? 18 : 263, 748, font);
  line('branch', upper(form.branch)); line('date', form.date); line('figures', amount.display); line('words1', line1); line('words2', line2); line('account', form.account); line('cheque', form.cheque); line('name', upper(form.company)); line('addr1', upper(form.address1)); line('addr2', upper(form.address2)); line('mobile', form.mobile); line('beneficiary', upper(form.beneficiaryName)); line('beneAccount', form.beneficiaryAccount); line('bank', upper(form.beneficiaryBank)); line('ifsc', upper(form.ifsc)); line('branchAddress', upper(form.beneficiaryBranch)); line('ackName', upper(form.company)); line('ackBeneficiary', upper(form.beneficiaryName)); line('ackBank', upper(form.beneficiaryBank)); line('ackDate', form.date); line('ackAccount', form.beneficiaryAccount); line('ackAmount', amount.display);
}
function fillKotak(page: any, font: any, form: FormState, amount: NonNullable<ReturnType<typeof parseAmount>>) {
  const [line1, line2] = split(words(amount)); mark(page, form.mode === 'RTGS' ? 182 : 234, 777, font); write(page,449,742,form.date,font); write(page,137,719,upper(form.branch),font); write(page,149,680,form.account,font); write(page,422,680,form.cheque,font); write(page,122,666,amount.display,font); write(page,277,666,line1,font); write(page,28,653,line2,font); write(page,81,625,upper(form.purpose),font);
  const type: Record<string, number> = { CURRENT:171, SAVINGS:212, NRE:250, OD:280, CC:351, 'CREDIT CARD':426, LOAN:488, OTHER:523 }; mark(page,type[form.kotakAccountType] || 171,616,font); write(page,129,589,upper(form.beneficiaryName),font); write(page,421,589,form.beneficiaryAccount,font); write(page,157,572,form.beneficiaryAccount,font); write(page,362,572,upper(form.ifsc),font); write(page,55,555,upper(form.beneficiaryBank),font); write(page,328,555,upper(form.beneficiaryBranch),font); write(page,164,537,upper(form.beneficiaryLei),font); write(page,50,487,upper(form.company),font); write(page,120,89,upper(form.branch),font); write(page,418,89,form.date,font); write(page,259,62,amount.display,font); write(page,269,46,form.beneficiaryAccount,font); write(page,467,46,upper(form.beneficiaryBank),font);
}
function fillHdfc(page: any, font: any, form: FormState, amount: NonNullable<ReturnType<typeof parseAmount>>) {
  const [line1, line2] = split(words(amount)); mark(page,form.mode === 'RTGS' ? 54 : 244,954,font); write(page,463,946,form.date,font); write(page,80,846,upper(form.company),font); write(page,115,815,form.account,font); write(page,265,815,form.cheque,font); write(page,115,783,form.mobile,font); comb(page,242,756,330,20,upper(form.remitterLei),font); comb(page,156,724,147,8,form.remitterLeiExpiry,font); write(page,290,695,upper(`${form.address1} ${form.address2}`),font); write(page,387,679,upper(form.email),font); write(page,86,647,upper(form.beneficiaryName),font); write(page,458,647,form.beneficiaryContact,font); write(page,83,630,upper(form.beneficiaryAddress),font); comb(page,166,596,296,16,form.beneficiaryAccount,font); comb(page,166,565,296,16,form.beneficiaryAccount,font); write(page,155,542,upper(`${form.beneficiaryBank} ${form.beneficiaryBranch}`),font); write(page,409,542,upper(form.ifsc),font);
  const type: Record<string, number> = { RESIDENT:104, 'NON RESIDENT':158, FCRA:240 }; mark(page,type[form.hdfcAccountType] || 104,523,font); write(page,301,523,upper(form.purpose),font); comb(page,242,491,330,20,upper(form.beneficiaryLei),font); comb(page,156,459,147,8,form.beneficiaryLeiExpiry,font); write(page,207,426,amount.display,font); write(page,400,426,line1,font); write(page,83,409,line2,font); write(page,82,393,upper(form.purpose),font); mark(page,45,form.banv === 'VERIFY' ? 357 : 335,font); write(page,275,79,amount.display,font); write(page,202,62,form.cheque,font); write(page,270,45,form.beneficiaryAccount,font); write(page,415,45,upper(form.beneficiaryBank),font); write(page,106,28,upper(form.ifsc),font);
}
function fillSbi(page: any, font: any, form: FormState, amount: NonNullable<ReturnType<typeof parseAmount>>) {
  const [line1, line2] = split(words(amount)); mark(page,form.mode === 'RTGS' ? 523 : 468,440,font); write(page,592,444,form.date,font); write(page,545,420,upper(form.branch),font); write(page,351,405,amount.display,font); write(page,405,405,line1,font); write(page,272,390,line2,font); write(page,272,374,form.account,font); write(page,646,374,form.cheque,font); write(page,272,347,upper(form.beneficiaryName),font); write(page,272,332,upper(`${form.beneficiaryBank} ${form.beneficiaryBranch}`),font); comb(page,318,315,194,11,upper(form.ifsc),font); comb(page,405,295,315,18,form.beneficiaryAccount,font); comb(page,405,276,315,18,form.beneficiaryAccount,font); comb(page,370,250,350,20,upper(form.beneficiaryLei),font); comb(page,378,220,125,10,amount.display.replace(/,/g,''),font); write(page,272,176,words(amount),font,7,120); write(page,272,160,upper(form.company),font); comb(page,360,143,350,20,upper(form.remitterLei),font); write(page,272,116,upper(`${form.address1} ${form.address2}`),font); write(page,272,102,form.mobile,font); write(page,102,211,upper(form.beneficiaryName),font); write(page,102,181,form.beneficiaryAccount,font); write(page,102,165,form.beneficiaryAccount,font); write(page,102,150,upper(form.ifsc),font); write(page,102,135,upper(`${form.beneficiaryBank} ${form.beneficiaryBranch}`),font); write(page,102,104,amount.display,font); write(page,102,88,line1,font); write(page,102,73,line2,font);
}

const RtgsFormPage: React.FC = () => {
  const [form, setForm] = useState<FormState>(initialForm); const [notice, setNotice] = useState(''); const [update, setUpdate] = useState(''); const [working, setWorking] = useState(false);
  const set = (key: keyof FormState, value: string) => setForm(current => ({ ...current, [key]: value }));
  const parsed = useMemo(() => parseAmount(form.amount), [form.amount]);
  const bank = BANKS[form.bank];
  useEffect(() => { const profile = readProfiles()[form.bank] || blankProfile; setForm(current => ({ ...current, ...profile })); getRtgsTemplateStatus(form.bank).then((status: any) => setUpdate(status.updateAvailable ? `Updated official ${status.label} form detected. This screen stays on the reviewed template until AMBIC remaps it.` : '')).catch(() => setUpdate('Official template check unavailable. The bundled reviewed form remains selected.')); }, [form.bank]);
  const saveProfile = () => { const profiles = readProfiles(); profiles[form.bank] = { branch: form.branch, account: form.account, mobile: form.mobile, company: form.company, address1: form.address1, address2: form.address2, email: form.email }; localStorage.setItem(PROFILE_KEY, JSON.stringify(profiles)); setNotice(`${bank.label} profile saved only in this browser.`); };
  const lookupIfsc = async () => { const ifsc = upper(form.ifsc); if (!/^[A-Z]{4}0[A-Z0-9]{6}$/.test(ifsc)) return setNotice('Enter a valid 11-character IFSC.'); try { const response = await fetch(`https://ifsc.razorpay.com/${encodeURIComponent(ifsc)}`); if (!response.ok) throw new Error('IFSC not found.'); const item = await response.json(); setForm(current => ({ ...current, ifsc, beneficiaryBank: upper(item.BANK || ''), beneficiaryBranch: upper([item.BRANCH, item.ADDRESS].filter(Boolean).join(', ')) })); setNotice('Bank and branch filled from IFSC. Verify against beneficiary proof.'); } catch (error: any) { setNotice(error.message || 'IFSC lookup failed.'); } };
  const generate = async () => { const missing = [['branch', 'remitter branch'], ['account', 'remitter account'], ['company', 'remitter name'], ['beneficiaryName', 'beneficiary name'], ['beneficiaryAccount', 'beneficiary account'], ['ifsc', 'IFSC'], ['beneficiaryBank', 'beneficiary bank']].filter(([key]) => !String(form[key as keyof FormState]).trim()).map(([, label]) => label); if (!parsed) missing.unshift('valid amount'); if (form.mode === 'RTGS' && form.payment === 'CASH') missing.push('RTGS cannot use cash'); if (form.bank === 'kotak' && form.mode === 'RTGS' && !form.purpose.trim()) missing.push('Kotak RTGS purpose code'); if (missing.length) return setNotice(`Complete: ${[...new Set(missing)].join(', ')}.`); if (!parsed) return;
    setWorking(true); try { const source = await fetch(bank.asset); if (!source.ok) throw new Error('Approved bank template unavailable.'); const pdf = await PDFDocument.load(await source.arrayBuffer(), { updateMetadata: false }); const font = await pdf.embedFont(StandardFonts.Helvetica); if (form.bank === 'icici') fillIcici(pdf, font, form, parsed); if (form.bank === 'kotak') fillKotak(pdf.getPages()[0], font, form, parsed); if (form.bank === 'hdfc') fillHdfc(pdf.getPages()[0], font, form, parsed); if (form.bank === 'sbi') fillSbi(pdf.getPages()[0], font, form, parsed); const result = await pdf.save(); const fileBytes = result.buffer.slice(result.byteOffset, result.byteOffset + result.byteLength) as ArrayBuffer; const url = URL.createObjectURL(new Blob([fileBytes], { type: 'application/pdf' })); const link = document.createElement('a'); link.href = url; link.download = `${form.bank.toUpperCase()}-${form.date}-${form.beneficiaryAccount.slice(-4) || 'draft'}.pdf`; link.click(); URL.revokeObjectURL(url); saveProfile(); setNotice('Filled PDF downloaded. Review every field and sign manually before submission.'); } catch (error: any) { setNotice(error.message || 'Could not generate PDF.'); } finally { setWorking(false); }
  };
  const input = (key: keyof FormState, label: string, extra: React.InputHTMLAttributes<HTMLInputElement> = {}) => <label className={labelClass}>{label}<input className={fieldClass} value={String(form[key])} onChange={event => set(key, event.target.value)} {...extra} /></label>;
  return <div className="space-y-6"><header className="rounded-2xl bg-gradient-to-br from-slate-950 to-blue-950 p-6 text-white shadow-sm"><p className="text-[10px] font-black uppercase tracking-[.24em] text-cyan-300">AMBIC DIGITAL · Payment operations</p><h2 className="mt-2 text-3xl font-black">RTGS / NEFT Form Filler</h2><p className="mt-2 max-w-3xl text-sm text-slate-300">Uses the selected bank's reviewed official blank form. The generated PDF stays in this browser. Banking details are not stored on the notifier server.</p></header>
    {update && <div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm font-bold text-amber-900">{update}</div>}{notice && <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm font-bold text-blue-900">{notice}</div>}
    <section className="grid gap-6 rounded-2xl border border-gray-200 bg-white p-6 shadow-sm lg:grid-cols-2"><div className="space-y-4"><p className="text-xs font-black uppercase tracking-widest text-blue-700">Bank and transfer</p><label className={labelClass}>Bank form<select className={fieldClass} value={form.bank} onChange={event => set('bank', event.target.value)}>{Object.entries(BANKS).map(([id, item]) => <option key={id} value={id}>{item.label}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>Transfer mode<select className={fieldClass} value={form.mode} onChange={event => set('mode', event.target.value)}><option value="RTGS">RTGS</option><option value="NEFT">NEFT</option></select></label><label className={labelClass}>Payment mode<select className={fieldClass} value={form.payment} onChange={event => set('payment', event.target.value)}><option value="CHEQUE">Cheque</option><option value="CASH">Cash (NEFT only)</option></select></label></div><div className="grid gap-3 sm:grid-cols-2">{input('date','Date (DDMMYYYY)',{maxLength:8})}{input('cheque','Cheque number',{maxLength:20})}</div>{input('amount','Amount (INR)',{inputMode:'decimal',placeholder:'e.g. 300000'})}<div className="rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-900">{parsed ? words(parsed) : 'Enter a valid INR amount to generate words.'}</div>
      {(form.bank === 'kotak' || form.bank === 'sbi' || form.bank === 'hdfc') && input('purpose', form.bank === 'kotak' ? 'Purpose code / purpose (mandatory for Kotak RTGS)' : 'Transfer purpose')} {form.bank === 'kotak' && <label className={labelClass}>Beneficiary account type<select className={fieldClass} value={form.kotakAccountType} onChange={event => set('kotakAccountType', event.target.value)}>{['CURRENT','SAVINGS','NRE','OD','CC','CREDIT CARD','LOAN','OTHER'].map(item => <option key={item}>{item}</option>)}</select></label>} {form.bank === 'hdfc' && <div className="grid gap-3 sm:grid-cols-2"><label className={labelClass}>Beneficiary account type<select className={fieldClass} value={form.hdfcAccountType} onChange={event => set('hdfcAccountType', event.target.value)}><option value="RESIDENT">Resident</option><option value="NON RESIDENT">Non-resident</option><option value="FCRA">FCRA</option></select></label><label className={labelClass}>Beneficiary verification<select className={fieldClass} value={form.banv} onChange={event => set('banv', event.target.value)}><option value="VERIFY">HDFC Bank to verify</option><option value="CUSTOMER_VERIFIED">Verified by remitter</option></select></label></div>}</div>
      <div className="space-y-4"><p className="text-xs font-black uppercase tracking-widest text-emerald-700">Beneficiary</p>{input('beneficiaryName','Beneficiary name')}{input('beneficiaryAccount','Account number',{inputMode:'numeric'})}<div className="grid gap-3 sm:grid-cols-[1fr_auto]"><label className={labelClass}>IFSC<input className={fieldClass} value={form.ifsc} onChange={event => set('ifsc', upper(event.target.value))} maxLength={11} /></label><button type="button" onClick={lookupIfsc} className="mt-5 rounded-xl bg-blue-700 px-4 py-3 text-xs font-black uppercase text-white">Look up IFSC</button></div>{input('beneficiaryBank','Bank name')}{input('beneficiaryBranch','Bank branch / address')}{form.bank === 'hdfc' && <>{input('beneficiaryContact','Beneficiary contact number',{inputMode:'tel'})}{input('beneficiaryAddress','Beneficiary address')}</>}{(form.bank === 'kotak' || form.bank === 'hdfc' || form.bank === 'sbi') && <div className="grid gap-3 sm:grid-cols-2">{input('remitterLei','Remitter LEI (if required)')}{input('beneficiaryLei','Beneficiary LEI (if required)')}{form.bank === 'hdfc' && <>{input('remitterLeiExpiry','Remitter LEI expiry',{maxLength:8})}{input('beneficiaryLeiExpiry','Beneficiary LEI expiry',{maxLength:8})}</>}</div>}</div></section>
    <section className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-violet-700">Remitter profile</p><p className="mt-1 text-sm text-gray-500">Saved only on this browser, separately for each bank. No account data is embedded in this public dashboard.</p></div><button type="button" onClick={saveProfile} className="rounded-xl border border-violet-200 bg-violet-50 px-4 py-3 text-xs font-black uppercase text-violet-800">Save {bank.label} profile</button></div><div className="grid gap-3 md:grid-cols-3">{input('branch',`${bank.label} branch`)}{input('account','Remitter account number',{inputMode:'numeric'})}{input('mobile','Mobile',{inputMode:'tel'})}</div><div className="mt-3 grid gap-3 md:grid-cols-2">{input('company','Company / remitter name')}{input('email','Remitter email',{type:'email'})}{input('address1','Address line 1')}{input('address2','Address line 2')}</div></section>
    <section className="flex flex-col gap-4 rounded-2xl border border-gray-200 bg-slate-950 p-6 text-white shadow-sm md:flex-row md:items-center md:justify-between"><p className="max-w-3xl text-sm text-slate-300">Verify beneficiary name, account number, IFSC, amount, selected bank form and bank-specific fields. IFSC lookup does not establish account ownership. Review and sign manually.</p><button type="button" disabled={working} onClick={generate} className="rounded-xl bg-cyan-400 px-5 py-3 text-xs font-black uppercase text-slate-950 disabled:opacity-60">{working ? 'Generating…' : 'Generate filled PDF'}</button></section>
  </div>;
};

export default RtgsFormPage;
