<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ambic.PrintCore\Ambic.PrintCore.csproj" />
    <ProjectReference Include="..\Ambic.PrintAdapters.Pdf\Ambic.PrintAdapters.Pdf.csproj" />
  </ItemGroup>

</Project>
